if(MTS_BUILD_CORE_LIBS)
    add_subdirectory(libcore)
    add_subdirectory(librender)
    add_subdirectory(libhw)
    add_subdirectory(libbidir)
endif()

if(MTS_BUILD_APPS)
    add_subdirectory(mitsuba)
endif()

if(MTS_HAS_COLLADA)
    add_subdirectory(converter)
endif()

if(MTS_HAS_QT)
    add_subdirectory(mtsgui)
endif()

if(MTS_HAS_PYTHON)
    add_subdirectory(libpython)
endif()

if(MTS_BUILD_BSDF_PLUGINS)
    add_subdirectory(bsdfs)
endif()

if(MTS_BUILD_PLUGIN_GROUPS)
    add_subdirectory(utils)
    add_subdirectory(phase)
    add_subdirectory(shapes)
    add_subdirectory(samplers)
    add_subdirectory(rfilters)
    add_subdirectory(films)
    add_subdirectory(sensors)
    add_subdirectory(emitters)
    add_subdirectory(medium)
    add_subdirectory(volume)
    add_subdirectory(subsurface)
    add_subdirectory(textures)
    add_subdirectory(integrators)
endif()

if(MTS_BUILD_TEST_PLUGINS)
    add_subdirectory(tests)
endif()
